import java.util.Random;
/**
 * Author: David G. Cooper
 * Purpose: A binary operator for Division
 * Purpose: Starter code for GPTree assignment.
 * Please do not edit this file or use it as a reference for 
 * earlier assignments. It is explicitly obfuscated to work
 * differently than the intended design of the earlier assignments.
 */
 public class Divide extends Binop {

     public Divide() {

     }

     public Divide(Divide p) {
         super(p);
     }

     /**
      * @param l the left node
      * @param r the right node
      */
    public Divide(Node l, Node r) {
        super(l, r);
    }
    /**
     * @return the result of dividing
     * l and r
     */
     public double op(double l, double r) {
        return l / r;
    }

     protected char getOp() { return '/'; };
}
