/**
 * Author: David G. Cooper
 * Purpose: Starter code for GPTree assignment.
 * Please do not edit this file or use it as a reference for 
 * earlier assignments. It is explicitly obfuscated to work
 * differently than the intended design of the earlier assignments.
 */
public class TerminalFactory {
    public TerminalFactory(int n) {
        NodeFactory.setNumInd(n);
    }
}
